AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Globals:
    Function:
        Timeout: 3
Resources:
    SampleFunction:
        Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
        Properties:
            CodeUri: ./sample_lambda/
            Handler: index.lambda_handler
            Runtime: python3.6
            Events:
              Api:
                Type: Api
                Properties:
                  Path: /
                  Method: any
            # Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
            #     Variables: